baseURL = "http://artcade.blog/"
languageCode = "fr"
title = "Artcade"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "fr"

[params]
    author = "Pizzacus"
    subtitle = "Une explorations des technologies provenant de l'aube du jeu vidéo"
    copyrightBy = "par Pizzacus"
    showSocialMedia = false
    enableMomentJs = true