baseURL = "https://artcade.blog/"
languageCode = "fr"
title = "Artcade"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "fr"

[params]
    author = "Pizzacus"
    description = "Artcade - Le savoir-faire à l'aube du jeu vidéo"
    subtitle = "Une exploration du savoir-faire à l'aube du jeu vidéo"
    copyrightBy = "par Pizzacus"
    showSocialMedia = false
    enableMomentJs = true
    customImage = "alien.webp"
    showReadingTime = true
    copyrightUseCurrentYear = true
    css_modules = ["css/custom.css"]

[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"